name = "Vanilla Resewn"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a107164806c3cb0f03e244a43bc2c3d16e7d9c17e8ade8417c7e9c01251282"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
