name = "Vanilla Resewn"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "291f899c4722c700c8c85a384595349b933aae9e5b79ad39d1b5fa86a6f6bdfe"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
