name = "Vanilla Resewn"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70907c152699878325118e5dd3f8ca8637132cd9f7f146caba46061228b8a7c3"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
