name = "Vanilla Resewn"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05090fcddd812fb72e20a2e5eb0f628120753fa8bd91f72aaa36a83cb96ab6bb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
