name = "Vanilla Resewn"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f047da553cb3ac8ccd0628af706f45325c6c192ad7ae498a0ee3df283edfe8c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
