name = "Vanilla Resewn"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee941cb2a541494dd43a2ea54305cd287913f896c7857b3df5e979e0aa9d5119"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
